# Generated by Django 3.2 on 2021-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
            ],
        ),
    ]
